"""add permissions to roles

Revision ID: 2c813a7d0cb6
Revises: aeccefb21af3
Create Date: 2021-08-24 23:21:41.169872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c813a7d0cb6'
down_revision = 'aeccefb21af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Role', sa.Column('permissions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Role', 'permissions')
    # ### end Alembic commands ###
