"""add contact number field to user model

Revision ID: 30366f8d2c42
Revises: 57dd217143c9
Create Date: 2021-10-17 11:00:16.504431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30366f8d2c42'
down_revision = '57dd217143c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_User_contact_number'), ['contact_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_contact_number'))
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
