"""add start and end time strings to booking

Revision ID: 57dd217143c9
Revises: c47c453f45b1
Create Date: 2021-09-08 17:20:47.681458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57dd217143c9'
down_revision = 'c47c453f45b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.String(length=16), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Booking', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
