"""add latitude and longitude to CarBay and ParkingLot

Revision ID: 6c776edec699
Revises: 2c813a7d0cb6
Create Date: 2021-08-31 18:50:52.632729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c776edec699'
down_revision = '2c813a7d0cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CarBay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.create_unique_constraint("uq_bay_location", ['latitude', 'longitude'])

    with op.batch_alter_table('ParkingLot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.create_unique_constraint("uq_lot_location", ['latitude', 'longitude'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ParkingLot', schema=None) as batch_op:
        batch_op.drop_constraint("uq_lot_location", type_='unique')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('CarBay', schema=None) as batch_op:
        batch_op.drop_constraint("uq_bay_location", type_='unique')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
