"""remove unique constraint from first and last name of user

Revision ID: aeccefb21af3
Revises: 5eacdf675440
Create Date: 2021-08-21 23:54:51.246197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeccefb21af3'
down_revision = '5eacdf675440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_User_first_name', table_name='User')
    op.create_index(op.f('ix_User_first_name'), 'User', ['first_name'], unique=False)
    op.drop_index('ix_User_last_name', table_name='User')
    op.create_index(op.f('ix_User_last_name'), 'User', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_last_name'), table_name='User')
    op.create_index('ix_User_last_name', 'User', ['last_name'], unique=False)
    op.drop_index(op.f('ix_User_first_name'), table_name='User')
    op.create_index('ix_User_first_name', 'User', ['first_name'], unique=False)
    # ### end Alembic commands ###
