"""add ParkingLot model

Revision ID: d628e5cc1e74
Revises: 
Create Date: 2021-08-14 23:17:30.603073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd628e5cc1e74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ParkingLot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ParkingLot')
    # ### end Alembic commands ###
