"""add car bay model

Revision ID: 52ea9dfb30ac
Revises: d628e5cc1e74
Create Date: 2021-08-15 00:18:20.180241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ea9dfb30ac'
down_revision = 'd628e5cc1e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CarBay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bay_number', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['ParkingLot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CarBay')
    # ### end Alembic commands ###
